# Generated by Django 5.0.7 on 2024-08-05 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BIRREC',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('rdate', models.DateField(default=datetime.date(2000, 1, 1), null=True)),
                ('name', models.CharField(max_length=50)),
                ('amtwrd', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=50)),
                ('birsales', models.CharField(blank=True, max_length=50, null=True)),
                ('biramt', models.CharField(max_length=50)),
                ('birdue', models.CharField(max_length=50)),
                ('tdate', models.DateField(default=datetime.date(2000, 1, 1), null=True)),
                ('ttime', models.CharField(max_length=15)),
                ('desc', models.CharField(max_length=255)),
                ('account_id', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=5)),
                ('day', models.CharField(max_length=5)),
                ('yr', models.CharField(max_length=10)),
                ('branch_name', models.CharField(max_length=20)),
                ('status', models.CharField(default='NP', max_length=2)),
                ('p_date', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpCode', models.CharField(max_length=20, unique=True)),
                ('Firstname', models.CharField(max_length=20)),
                ('Middlename', models.CharField(max_length=20)),
                ('Lastname', models.CharField(max_length=20)),
                ('EmpImg', models.ImageField(blank=True, null=True, upload_to='employee_images/')),
                ('DateofBirth', models.DateField(default=datetime.date(2000, 1, 1), null=True)),
                ('Gender', models.CharField(default='Male', max_length=8)),
                ('CivilStatus', models.CharField(default='N/A', max_length=10)),
                ('Address', models.CharField(default='N/D', max_length=50)),
                ('Position', models.CharField(max_length=50)),
                ('Department', models.CharField(blank=True, default='N/A', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('start_date', models.DateField(default=datetime.date(2000, 1, 1), null=True)),
                ('end_date', models.DateField(default=datetime.date(2000, 1, 1), null=True)),
                ('start_time', models.CharField(default='N/D', max_length=20)),
                ('end_time', models.CharField(default='N/D', max_length=20)),
                ('cottage', models.CharField(max_length=100, null=True)),
                ('room', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
