# Generated by Django 5.0.7 on 2024-08-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='past_due',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('pd_id', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('branch_name', models.CharField(max_length=20)),
                ('account_id', models.CharField(max_length=20)),
                ('pd_first_name', models.CharField(max_length=20)),
                ('pd_middle_name', models.CharField(max_length=20)),
                ('pd_last_name', models.CharField(max_length=20)),
                ('pd_balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('pd_bank', models.CharField(max_length=15)),
                ('pd_class', models.CharField(max_length=5)),
                ('pd_status', models.CharField(max_length=5)),
                ('pd_refdate', models.DateField(blank=True, null=True)),
                ('pd_age', models.CharField(max_length=5)),
                ('pd_address', models.CharField(max_length=200)),
                ('pd_type', models.CharField(max_length=5)),
                ('date_change', models.DateField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('old_account_no', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'past_due',
            },
        ),
        migrations.CreateModel(
            name='past_due_ledger',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20)),
                ('branch_name', models.CharField(max_length=20)),
                ('account_id', models.CharField(max_length=20)),
                ('pdl_date', models.DateField(blank=True, null=True)),
                ('pdl_refno', models.CharField(max_length=50)),
                ('pdl_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('pdl_credit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('pdl_debit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('pay_mis', models.IntegerField()),
                ('include_week', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('old_account_no', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'past_due_ledger',
            },
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('can_delete_employee', 'Can delete employee')]},
        ),
    ]
