# Generated by Django 5.0.7 on 2024-08-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_past_due_past_due_ledger_alter_employee_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='past_due',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='past_due_ledger',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
