# Generated by Django 5.0.7 on 2024-08-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_past_due_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ssp_ledger',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('ssp_ref', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True)),
                ('ssp_folio', models.CharField(max_length=20)),
                ('ssp_tcode', models.IntegerField()),
                ('ssp_tdate', models.DateField(blank=True, null=True)),
                ('ssp_desc', models.CharField(max_length=20)),
                ('ssp_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('ssp_old_ref', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True)),
                ('ssp_atm_bal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'ssp_ledger',
            },
        ),
    ]
